{
    "Title": "The Hateful Eight",
    "Year": "2015",
    "Rated": "R",
    "Released": "30 Dec 2015",
    "Runtime": "168 min",
    "Genre": "Crime, Drama, Mystery",
    "Director": "Quentin Tarantino",
    "Writer": "Quentin Tarantino",
    "Actors": "Samuel L. Jackson, Kurt Russell, Jennifer Jason Leigh",
    "Plot": "In the dead of a Wyoming winter, a bounty hunter and his prisoner find shelter in a cabin currently inhabited by a collection of nefarious characters.",
    "Language": "English, Spanish, French, Persian",
    "Country": "United States",
    "Awards": "Won 1 Oscar. 46 wins & 116 nominations total",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMjA1MTc1NTg5NV5BMl5BanBnXkFtZTgwOTM2MDEzNzE@._V1_SX300.jpg",
    "Ratings": [
        {"Source": "Internet Movie Database", "Value": "7.8/10"},
        {"Source": "Rotten Tomatoes", "Value": "74%"},
        {"Source": "Metacritic", "Value": "68/100"}
    ],
    "Metascore": "68",
    "imdbRating": "7.8",
    "imdbVotes": "699,279",
    "imdbID": "tt3460252",
    "Type": "movie",
    "DVD": "N/A",
    "BoxOffice": "$54,117,416",
    "Production": "N/A",
    "Website": "N/A",
    "Response": "True"
}